internacionalizacion.etiquetas = {
	es : {
		titulo1: "Circo",
		titulo2: "neuronal",
		titulo: "Circo neuronal",
		presentacion: "Universidad de Oviedo presenta",
		descubre: "Descubre tu destreza mental",
		comenzar: "COMENZAR",
		creado: "creado por",
		img_gratis: 'img/gratis.png',
		img_3minutos: 'img/3minutos.png',
		instrucciones_numeros: 'Pulsa sobre cada uno de los patos en el orden que marcan los números del 1 al 20.',
		titulo_prueba_1: 'P r u e b a  1',
		nombre_prueba_1: 'C i f r a s  v e l o c e s',
		instrucciones_topos: 'Pulsa sobre cada topo según vayan saliendo de su madriguera.',
		titulo_prueba_2: 'P r u e b a  2',
		nombre_prueba_2: 'G o l p e a  a l  t o p o',
		instrucciones_palabras: 'Escribe las palabras que contienen los patos.',
		titulo_prueba_3: 'P r u e b a  3',
		nombre_prueba_3: 'T i r o  a l  p a t o',
		continuar: "Continuar",
		pulsaCirculo: "Pulsa un círculo",
		paraContinuar: "para continuar",
		pulsaDiana: "Pulsa una diana",
		acrobata1: "Ayuda a los acróbatas a cruzar al otro lado.",
		acrobata2: "Gira el tablón central para completar la pista.",
		aceptar: "Aceptar",
		pruebaFinalizada: "Prueba finalizada",
		girar_dispositivo: "Orienta el dispositivo en posición vertical.",
		escribe: "Escribe aquí",
		tu_edad_mental: "Tu edad mental es",
		pulsa_finalizar: "Pulsa para finalizar",
		gracias: "Gracias por participar",
		comparte: "Comparte esto",
		descubre_en: "Descubre tu destreza mental en ",
		es_gratis: ". Es GRATIS."
	},
	
	en : {
		titulo1: "Neuronal",
		titulo2: "circus",
		titulo: "Neuronal circus",
		presentacion: "University of Oviedo presents",
		descubre: "Discover your mental skills",
		comenzar: "START",
		creado: "created by",
		img_gratis: 'img/free.png',
		img_3minutos: 'img/only.png',
		instrucciones_numeros: 'Click on each duck in order from 1 to 20.',
		titulo_prueba_1: 'T e s t  #1',
		nombre_prueba_1: 'Q u i c k  N u m b e r s',
		instrucciones_topos: 'Click on the moles as they emerge from their holes.',
		titulo_prueba_2: 'T e s t  #2',
		nombre_prueba_2: 'W h a c k   a  M o l e',
		instrucciones_palabras: 'Write the words contained in the ducks.',
		titulo_prueba_3: 'T e s t  #3',
		nombre_prueba_3: 'D u c k  S h o o t',
		continuar: "Continue",
		pulsaCirculo: "Click on one circle",
		paraContinuar: "to continue",
		pulsaDiana: "Click on one target",
		acrobata1: "Help the acrobats to reach the other side.",
		acrobata2: "Spin around the central board to complete the track.",
		aceptar: "Aceptar",
		pruebaFinalizada: "Test Over",
		girar_dispositivo: "Locate the device in vertical position.",
		escribe: "Write in here",
		tu_edad_mental: "Your mental age is",
		pulsa_finalizar: "Click to finish",
		gracias: "Thank you for participating",
		comparte: "Share this",
		descubre_en: "Discover your mental skills in ",
		es_gratis: ". It's FREE."
	}	
};